import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
	title: "Frontend Challenge",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<div className="font-sans items-center justify-center min-h-screen p-8 pb-20 gap-16 sm:p-20">
					<div className="flex items-center justify-center">
						{children}
					</div>
				</div>
			</body>
		</html>
	);
}
